export enum ErrorCode {
  SUCCESS = 0,
  INSUFFICIENT_BALANCE = 1,
  ORDER_NOT_FOUND = 2,
  INVALID_PRICE = 3,
  INVALID_QTY = 4,
  INVALID_SIDE = 5,
  INVALID_TYPE = 6,
  INVALID_SYMBOL = 7,
  ORDER_POOL_EXHAUSTED = 8,
}
